name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cschleiden/replace-tokens@v1
        with:
          files: '["**/*.json"]'
        env:
          DATABASE_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
          DATABASE_DATABASE: ${{secrets.DATABASE_DATABASE}}
          DATABASE_USERNAME: ${{secrets.DATABASE_USERNAME}}
          DATABASE_CLUSTER: ${{secrets.DATABASE_CLUSTER}}
          IMGUR_AUTH: ${{secrets.IMGUR_AUTH}}
          AUTH_API_KEY: ${{secrets.AUTH_API_KEY}}
          AUTH_SECRET_KEY: ${{secrets.AUTH_SECRET_KEY}}
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "libras-o-jogo"
          heroku_email: "gabrielrsantoss@icloud.com"